openapi: 3.0.0
x-stoplight:
  id: k7hnmdslxpqml
info:
  title: detectlabel
  version: '1.0'
  description: Detect labels in image
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
    url: www.leorbrenman.com
  license:
    name: Apache 2.0
    url: www.leorbrenman.com
servers:
  - url: 'http://localhost:8080/api'
    description: Local
paths:
  /detectlabels:
    post:
      summary: ''
      operationId: post-detectlabels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/detectLabelResponse.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.yaml
      description: Detect labels in Base64 encoded image
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
              required:
                - image
components:
  schemas: {}
  securitySchemes:
    apikey:
      name: apikey
      type: apiKey
      in: query
security:
  - apikey: []
tags:
  - name: detectLabel
    description: Detect labels
