openapi: 3.0.0
x-stoplight:
  id: k7hnmdslxpqml
info:
  title: detectlabel
  version: '1.0'
  description: Detect labels in image
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
    url: www.leorbrenman.com
  license:
    name: Apache 2.0
    url: www.leorbrenman.com
servers:
  - url: 'http://localhost:8080/api'
    description: Local
paths:
  /detectlabels:
    get:
      summary: Your GET endpoint
      tags:
        - detectLabel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/detectLabelResponse.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-detectlabels
      description: Detect labels in your (Base64 encoded) image
      parameters:
        - schema:
            type: string
          in: query
          name: image
          description: Base64 encoded image to detect labels in
components:
  schemas: {}
  securitySchemes:
    apikey:
      name: apikey
      type: apiKey
      in: query
security:
  - apikey: []
tags:
  - name: detectLabel
    description: Detect labels
